server:
  port: 8081

spring:
  application:
    name: CALIFICACION-SERVICE
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017
      database: microservicios

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/